# Generated by Django 2.2.24 on 2021-10-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deposited_by', models.CharField(max_length=36)),
                ('status', models.BooleanField(default=False)),
                ('deposited_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('reference_id', models.CharField(max_length=36, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owned_by', models.CharField(max_length=36, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('enabled_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('withdrawn_by', models.CharField(max_length=36)),
                ('status', models.BooleanField(default=False)),
                ('withdrawn_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('reference_id', models.CharField(max_length=36, unique=True)),
            ],
        ),
    ]
